W0617 11:17:09.881000 3436360 site-packages/torch/distributed/run.py:792] 
W0617 11:17:09.881000 3436360 site-packages/torch/distributed/run.py:792] *****************************************
W0617 11:17:09.881000 3436360 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0617 11:17:09.881000 3436360 site-packages/torch/distributed/run.py:792] *****************************************
Using DDP across 2 GPUs.
usage: __main__.py [-h] [--batch_size int] [--grad_acc_steps int]
                   [--micro_acc_steps int] [--loss_fn {ce,fvu,kl}]
                   [--optimizer {adam,muon,signum}] [--lr [float]]
                   [--lr_warmup_steps int] [--k_decay_steps int]
                   [--auxk_alpha float] [--dead_feature_threshold int]
                   [--hookpoints list] [--init_seeds list] [--layers list]
                   [--layer_stride int] [--distribute_modules bool]
                   [--save_every int] [--save_best bool] [--finetune [str]]
                   [--log_to_wandb bool] [--run_name [str]]
                   [--wandb_log_frequency int] [--save_dir str] [--split str]
                   [--ctx_len int] [--hf_token [str]] [--revision [str]]
                   [--load_in_8bit bool] [--max_examples [int]]
                   [--resume bool] [--text_column str] [--shuffle_seed int]
                   [--data_preprocessing_num_proc int]
                   [--activation {groupmax,topk}] [--expansion_factor int]
                   [--normalize_decoder bool] [--num_latents int] [-k int]
                   [--multi_topk bool] [--skip_connection bool]
                   [--transcode bool]
                   str str
__main__.py: error: unrecognized arguments: fvu kl
usage: __main__.py [-h] [--batch_size int] [--grad_acc_steps int]
                   [--micro_acc_steps int] [--loss_fn {ce,fvu,kl}]
                   [--optimizer {adam,muon,signum}] [--lr [float]]
                   [--lr_warmup_steps int] [--k_decay_steps int]
                   [--auxk_alpha float] [--dead_feature_threshold int]
                   [--hookpoints list] [--init_seeds list] [--layers list]
                   [--layer_stride int] [--distribute_modules bool]
                   [--save_every int] [--save_best bool] [--finetune [str]]
                   [--log_to_wandb bool] [--run_name [str]]
                   [--wandb_log_frequency int] [--save_dir str] [--split str]
                   [--ctx_len int] [--hf_token [str]] [--revision [str]]
                   [--load_in_8bit bool] [--max_examples [int]]
                   [--resume bool] [--text_column str] [--shuffle_seed int]
                   [--data_preprocessing_num_proc int]
                   [--activation {groupmax,topk}] [--expansion_factor int]
                   [--normalize_decoder bool] [--num_latents int] [-k int]
                   [--multi_topk bool] [--skip_connection bool]
                   [--transcode bool]
                   str str
__main__.py: error: unrecognized arguments: fvu kl
[rank0]:[W617 11:17:14.039967790 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0617 11:17:15.604000 3436360 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3436370 closing signal SIGTERM
E0617 11:17:15.820000 3436360 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 2) local_rank: 0 (pid: 3436369) of binary: /home/tilman.kerl/miniconda3/envs/refusal/bin/python
Traceback (most recent call last):
  File "/home/tilman.kerl/miniconda3/envs/refusal/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tilman.kerl/miniconda3/envs/refusal/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/tilman.kerl/miniconda3/envs/refusal/lib/python3.11/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/home/tilman.kerl/miniconda3/envs/refusal/lib/python3.11/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/home/tilman.kerl/miniconda3/envs/refusal/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tilman.kerl/miniconda3/envs/refusal/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
sparsify FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-17_11:17:15
  host      : avm-a100-qs-9.novalocal
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 3436369)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
